create table participations_messages (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  message bytea not null,
  expired_at timestamp with time zone not null default (now() + '90 days'::interval),
  sender_id uuid not null default auth.uid (),
  recipient_id uuid not null,
  participation_id bigint not null,
  constraint messages_pkey primary key (id),
  constraint participations_messages_participation_id_fkey foreign KEY (participation_id) references participations (id) on delete CASCADE,
  constraint participations_messages_sender_id_fkey foreign KEY (sender_id) references auth.users (id) on delete CASCADE,
  constraint participations_messages_recipient_id_fkey foreign KEY (recipient_id) references auth.users (id),
  constraint sender_not_equal_recipient check (sender_id <> recipient_id)
);

ALTER TABLE participations_messages ENABLE ROW LEVEL SECURITY;

create policy "Allow message access for sender or recipient"
    on public.participations_messages
    as permissive
    for select
    to authenticated
    using (((select auth.uid()) = sender_id) or ((select auth.uid()) = recipient_id));

create policy "Allow participants or owners to insert messages"
    on public.participations_messages
    as permissive
    for insert
    to authenticated
    with check (
        ((select auth.uid()) = sender_id)
        and exists (
            select 1
            from public.participations p
            join public.tasks t on t.id = p.task_id
            where p.id = participation_id
                and (p.user_id = (select auth.uid()) or t.user_id = (select auth.uid()))
                and (recipient_id = p.user_id or recipient_id = t.user_id)
        )
    );

