create table public.participations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  task_id bigint not null,
  user_id uuid not null default auth.uid (),
  status public.task_participation_status not null default 'pending'::task_participation_status,
  updated_at timestamp with time zone not null default now(),
  constraint participations_pkey primary key (id),
  constraint participations_task_user_unique unique (task_id, user_id),
  constraint participations_task_id_fkey foreign KEY (task_id) references tasks (id) on update CASCADE on delete CASCADE,
  constraint participations_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

ALTER TABLE participations ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view items for their tasks only"
on "public"."participations"
as PERMISSIVE
for SELECT
to authenticated
using (
  is_my_task(participations.task_id) OR (user_id = (SELECT auth.uid() as uid))
);

create policy "Enable update for task owner or participation owner only"
on "public"."participations"
as PERMISSIVE
for UPDATE
to authenticated
using (
  is_my_task(participations.task_id) OR (user_id = (SELECT auth.uid() as uid))
);

create policy "Enable insert for users based on user_id"
on "public"."participations"
as PERMISSIVE
for INSERT
to authenticated
with check (
  (( SELECT auth.uid() AS uid) = user_id)
);

create function set_updated_at_column()
  returns trigger
  language plpgsql
  security definer
  set search_path = ''
  as $$
  begin
    new.updated_at = now();
    return new;
  end;
  $$;

create trigger set_updated_at_trigger
  before update on public.participations
  for each row
  execute function set_updated_at_column();

create or replace function create_friend_after_participation()
returns trigger 
  language plpgsql
  security definer
  set search_path = ''
as $$
declare
  task_owner uuid;
begin
  select user_id into task_owner
  from public.tasks
  where id = new.task_id;

  if task_owner is not null and task_owner <> new.user_id then
    insert into public.friends (user_id, friend_id)
    values (new.user_id, task_owner)
    on conflict do nothing;
  end if;

  return new;
end;
$$;

create trigger create_friend_after_participation_trigger
after insert on participations
for each row
execute function create_friend_after_participation();

create or replace function create_secret_key_for_participation()
returns trigger 
  language plpgsql
  security definer
  set search_path = public, extensions
as $$
begin
  perform vault.create_secret(encode(extensions.gen_random_bytes(24), 'hex'), 'participation:' || new.id::text);
  return new;
end;
$$;

create trigger create_secret_key_after_participation_trigger
after insert on participations
for each row
execute function create_secret_key_for_participation();

create or replace view my_participations with (security_invoker = on) as
  select
  p.id,
  p.status,
  t.title as task_title,
  t.description as task_description,
  t.type as task_type,
  t.repeated_days as task_repeated_days
from
  participations p
  join tasks t on t.id = p.task_id
where
  p.user_id = (
    select
      auth.uid ()
  );