CREATE TYPE task_interest_status AS ENUM ('pending', 'accepted', 'declined');

create table public.tasks_interests (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  task_id bigint not null,
  user_id uuid not null default auth.uid (),
  status public.task_interest_status not null default 'pending'::task_interest_status,
  updated_at timestamp with time zone not null default now(),
  constraint tasks_interests_pkey primary key (id),
  constraint tasks_interests_task_user_unique unique (task_id, user_id),
  constraint tasks_interests_task_id_fkey foreign KEY (task_id) references tasks (id) on update CASCADE on delete CASCADE,
  constraint tasks_interests_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
)

alter policy "Enable users to view their own data only"
on "public"."tasks_interests"
to authenticated
using (
  (( SELECT auth.uid() AS uid) = user_id)
);

alter policy "Enable insert for users based on user_id"
on "public"."tasks_interests"
to authenticated
with check (
  (( SELECT auth.uid() AS uid) = user_id)
);

create function set_updated_at_column()
  returns trigger
  language plpgsql
  security definer
  set search_path = ''
  as $$
  begin
    new.updated_at = now();
    return new;
  end;
  $$;

create trigger set_updated_at_trigger
  before update on public.tasks_interests
  for each row
  execute function set_updated_at_column();