CREATE TYPE task_type AS ENUM ('offer', 'request');

create table tasks (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  type task_type not null,
  title text not null,
  description text null,
  repeated_days text[] null,
  created_at timestamp with time zone not null default now(),
  location gis.geography(POINT) not null,
  constraint tasks_pkey primary key (id),
  constraint tasks_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

create index tasks_geo_index
  on tasks
  using GIST (location);

create or replace function get_nearby_tasks (
  user_lat double precision,
  user_lng double precision,
  distance_meters int
) returns table (
  id public.tasks.id % type,
  user_id public.tasks.user_id % type,
  type public.tasks.type % type,
  title public.tasks.title % type,
  description public.tasks.description % type,
  repeated_days public.tasks.repeated_days % type,
  is_me boolean,
  distance_meters int
)
set search_path = '' language sql as $$
select
  id,
  user_id,
  type,
  title,
  description,
  repeated_days,
  public.is_me(tasks.user_id) as is_me,
  round(gis.st_distance(public.tasks.location, gis.st_point(user_lng, user_lat)::gis.geography))::int as distance_meters
from
  public.tasks
  where gis.ST_DWithin(
        location,
        gis.ST_SetSRID(gis.ST_MakePoint(user_lng, user_lat), 4326)::gis.geography,
        distance_meters
    )
  order by location operator(gis.<->) gis.st_point(user_lng, user_lat)::gis.geography;
$$;