CREATE TYPE task_type AS ENUM ('offer', 'request');
CREATE TYPE task_day AS ENUM ('sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat');
CREATE TYPE task_participation_status AS ENUM ('pending', 'accepted', 'declined', 'completed');

create table tasks (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  type task_type not null,
  title text not null,
  description text null,
  repeated_days task_day[] null,
  created_at timestamp with time zone not null default now(),
  location gis.geography(POINT) not null,
  constraint tasks_pkey primary key (id),
  constraint tasks_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE,
  constraint tasks_title_check check ((length(title) < 200)),
  constraint tasks_description_check check ((length(description) < 1000))
);

create index tasks_geo_index
  on tasks
  using GIST (location);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

create policy "Enable read access for authenticated users"
  on "public"."tasks"
  as PERMISSIVE
  for SELECT
  to authenticated
  using (true);

create policy "Enable insert for users based on user_id"
  on "public"."tasks"
  as PERMISSIVE
  for INSERT
  to authenticated
  with check ((select auth.uid()) = user_id);

create or replace function is_my_task(task_id bigint)
returns boolean
language sql
set search_path = ''
as $$
  select exists (
    select 1
    from public.tasks
    where id = task_id
      and user_id = auth.uid()
  );
$$;

create or replace view my_tasks with (security_invoker = on) as
  select 
    id, 
    title, 
    description, 
    type, 
    repeated_days
  from tasks
  where tasks.user_id = (select auth.uid());