CREATE TYPE task_type AS ENUM ('offer', 'request');

create table tasks (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  type task_type not null,
  title text not null,
  description text null,
  repeated_days text[] null,
  created_at timestamp with time zone not null default now(),
  location gis.geography(POINT) not null,
  constraint tasks_pkey primary key (id),
  constraint tasks_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

create index tasks_geo_index
  on tasks
  using GIST (location);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

create policy "Enable read access for authenticated users"
  on "public"."tasks"
  as PERMISSIVE
  for SELECT
  to authenticated
  using (true);

create or replace function get_nearby_tasks (
  user_lat double precision,
  user_lng double precision,
  distance_meters int
) returns table (
  id public.tasks.id % type,
  user_id public.tasks.user_id % type,
  type public.tasks.type % type,
  title public.tasks.title % type,
  description public.tasks.description % type,
  repeated_days public.tasks.repeated_days % type,
  is_me boolean,
  distance_meters int
)
set search_path = '' language sql as $$
select
  id,
  user_id,
  type,
  title,
  description,
  repeated_days,
  public.is_me(tasks.user_id) as is_me,
  round(gis.st_distance(public.tasks.location, gis.st_point(user_lng, user_lat)::gis.geography))::int as distance_meters
from
  public.tasks
  where gis.ST_DWithin(
        location,
        gis.ST_SetSRID(gis.ST_MakePoint(user_lng, user_lat), 4326)::gis.geography,
        distance_meters
    ) AND user_id <> (SELECT auth.uid())
  order by location operator(gis.<->) gis.st_point(user_lng, user_lat)::gis.geography;
$$;

create or replace function get_task_details (
  task_id integer,
  current_lat double precision DEFAULT NULL,
  current_lng double precision DEFAULT NULL
) returns table (
  id public.tasks.id%type,
  user_id public.tasks.user_id%type,
  user_nickname public.users_public_details.nickname%type,
  user_avatar_url public.users_public_details.avatar_url%type,
  type public.tasks.type%type,
  title public.tasks.title%type,
  description public.tasks.description%type,
  repeated_days public.tasks.repeated_days%type,
  is_me boolean,
  distance_meters integer,
  lat double precision,
  lng double precision
)
language sql
set search_path = '' 
as $$
select
  t.id, 
  t.user_id,
  public_details.nickname,
  public_details.avatar_url,
  t.type, 
  t.title, 
  t.description, 
  t.repeated_days, 
  public.is_me(t.user_id) as is_me,
  CASE 
    WHEN current_lat IS NOT NULL AND current_lng IS NOT NULL THEN
      round(gis.st_distance(t.location, gis.st_point(current_lng, current_lat)::gis.geography))::int
    ELSE 
      NULL 
  END AS distance_meters,
  gis.st_y(t.location::gis.geometry) AS lat,
  gis.st_y(t.location::gis.geometry) as lat
FROM public.tasks t
LEFT JOIN public.users_public_details public_details
  ON public_details.user_id = t.user_id
WHERE t.id = task_id
$$;

create or replace view my_tasks as
  select 
    id, 
    title, 
    description, 
    type, 
    repeated_days
  from tasks
  where tasks.user_id = (select auth.uid());