create table public.users_public_details (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  nickname text not null,
  avatar_url text null,
  constraint users_public_details_pkey primary key (id),
  constraint users_public_details_nickname_key unique (nickname),
  constraint users_public_details_user_id_key unique (user_id),
  constraint users_public_details_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

ALTER TABLE users_public_details ENABLE ROW LEVEL SECURITY;

create policy "Enable read access for authenticated users"
  on "public"."users_public_details"
  as PERMISSIVE
  for SELECT
  to authenticated
  using (true);


create policy "Enable insert for users based on user_id"
on "public"."users_public_details"
as PERMISSIVE
for INSERT
to public
with check (
  (select auth.uid()) = user_id
);