create table public.users_private_details (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  email text not null,
  phone text null,
  constraint users_private_details_pkey primary key (id),
  constraint users_private_details_email_key unique (email),
  constraint users_private_details_phone_key unique (phone),
  constraint users_private_details_user_id_key unique (user_id),
  constraint users_private_details_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

ALTER TABLE users_private_details ENABLE ROW LEVEL SECURITY;

create policy "Enable users to view their own data only"
  on "public"."users_private_details"
  as PERMISSIVE
  for SELECT
  to authenticated
  using (( SELECT auth.uid() AS uid) = user_id);

create policy "Enable friends to view data"
  on "public"."users_private_details"
  as PERMISSIVE
  for SELECT
  to authenticated
  using (
    (EXISTS ( SELECT 1
      FROM friends f
    WHERE (f.friend_id = auth.uid())))
  );