create table public.users_private_details (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  phone text null,
  constraint users_private_details_pkey primary key (id),
  constraint users_private_details_phone_key unique (phone),
  constraint users_private_details_user_id_key unique (user_id),
  constraint users_private_details_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
);

ALTER TABLE users_private_details ENABLE ROW LEVEL SECURITY;

  create policy "Enable owners and those friends to view private details"
  on public.users_private_details
  as permissive
  for SELECT
  to authenticated
  using (
    user_id = (SELECT auth.uid())
    OR EXISTS (
      select 1
      from friends f
      where f.friend_id = (SELECT auth.uid())
    )
  );

create function create_user_private_details()
  returns trigger
  language plpgsql
  security definer
  set search_path = ''
  as $$
  begin
    insert into public.users_private_details(user_id)
    values (new.id);
    return new;
  end;
  $$;

create trigger auth_users_insert_trigger
  after insert on auth.users
  for each row
  execute function create_user_private_details();