create table "public"."friends" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "friend_id" uuid not null
);


alter table "public"."friends" enable row level security;

create table "public"."users_private_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "email" text not null,
    "phone" text
);


alter table "public"."users_private_details" enable row level security;

create table "public"."users_public_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "nickname" text not null
);


alter table "public"."users_public_details" enable row level security;

CREATE UNIQUE INDEX friends_pkey ON public.friends USING btree (user_id, friend_id);

CREATE UNIQUE INDEX users_private_details_email_key ON public.users_private_details USING btree (email);

CREATE UNIQUE INDEX users_private_details_phone_key ON public.users_private_details USING btree (phone);

CREATE UNIQUE INDEX users_private_details_pkey ON public.users_private_details USING btree (id);

CREATE UNIQUE INDEX users_private_details_user_id_key ON public.users_private_details USING btree (user_id);

CREATE UNIQUE INDEX users_public_details_nickname_key ON public.users_public_details USING btree (nickname);

CREATE UNIQUE INDEX users_public_details_pkey ON public.users_public_details USING btree (id);

CREATE UNIQUE INDEX users_public_details_user_id_key ON public.users_public_details USING btree (user_id);

alter table "public"."friends" add constraint "friends_pkey" PRIMARY KEY using index "friends_pkey";

alter table "public"."users_private_details" add constraint "users_private_details_pkey" PRIMARY KEY using index "users_private_details_pkey";

alter table "public"."users_public_details" add constraint "users_public_details_pkey" PRIMARY KEY using index "users_public_details_pkey";

alter table "public"."friends" add constraint "friends_friend_id_fkey" FOREIGN KEY (friend_id) REFERENCES auth.users(id) not valid;

alter table "public"."friends" validate constraint "friends_friend_id_fkey";

alter table "public"."friends" add constraint "friends_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."friends" validate constraint "friends_user_id_fkey";

alter table "public"."friends" add constraint "user_cannot_be_friend_to_self" CHECK ((user_id <> friend_id)) not valid;

alter table "public"."friends" validate constraint "user_cannot_be_friend_to_self";

alter table "public"."users_private_details" add constraint "users_private_details_email_key" UNIQUE using index "users_private_details_email_key";

alter table "public"."users_private_details" add constraint "users_private_details_phone_key" UNIQUE using index "users_private_details_phone_key";

alter table "public"."users_private_details" add constraint "users_private_details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_private_details" validate constraint "users_private_details_user_id_fkey";

alter table "public"."users_private_details" add constraint "users_private_details_user_id_key" UNIQUE using index "users_private_details_user_id_key";

alter table "public"."users_public_details" add constraint "users_public_details_nickname_key" UNIQUE using index "users_public_details_nickname_key";

alter table "public"."users_public_details" add constraint "users_public_details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_public_details" validate constraint "users_public_details_user_id_fkey";

alter table "public"."users_public_details" add constraint "users_public_details_user_id_key" UNIQUE using index "users_public_details_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_task_details(task_id integer, current_lat double precision DEFAULT NULL::double precision, current_lng double precision DEFAULT NULL::double precision)
 RETURNS TABLE(id bigint, user_id uuid, user_nickname text, type task_type, title text, description text, repeated_days text[], is_me boolean, distance_meters integer, lat double precision, lng double precision)
 LANGUAGE sql
 SET search_path TO ''
AS $function$
select
  t.id, 
  t.user_id,
  public_details.nickname,
  t.type, 
  t.title, 
  t.description, 
  t.repeated_days, 
  public.is_me(t.user_id) as is_me,
  CASE 
    WHEN current_lat IS NOT NULL AND current_lng IS NOT NULL THEN
      round(gis.st_distance(t.location, gis.st_point(current_lng, current_lat)::gis.geography))::int
    ELSE 
      NULL 
  END AS distance_meters,
  gis.st_y(t.location::gis.geometry) AS lat,
  gis.st_y(t.location::gis.geometry) as lat
FROM public.tasks t
LEFT JOIN public.users_public_details public_details
  ON public_details.user_id = t.user_id
WHERE t.id = task_id
$function$
;

grant delete on table "public"."friends" to "anon";

grant insert on table "public"."friends" to "anon";

grant references on table "public"."friends" to "anon";

grant select on table "public"."friends" to "anon";

grant trigger on table "public"."friends" to "anon";

grant truncate on table "public"."friends" to "anon";

grant update on table "public"."friends" to "anon";

grant delete on table "public"."friends" to "authenticated";

grant insert on table "public"."friends" to "authenticated";

grant references on table "public"."friends" to "authenticated";

grant select on table "public"."friends" to "authenticated";

grant trigger on table "public"."friends" to "authenticated";

grant truncate on table "public"."friends" to "authenticated";

grant update on table "public"."friends" to "authenticated";

grant delete on table "public"."friends" to "service_role";

grant insert on table "public"."friends" to "service_role";

grant references on table "public"."friends" to "service_role";

grant select on table "public"."friends" to "service_role";

grant trigger on table "public"."friends" to "service_role";

grant truncate on table "public"."friends" to "service_role";

grant update on table "public"."friends" to "service_role";

grant delete on table "public"."users_private_details" to "anon";

grant insert on table "public"."users_private_details" to "anon";

grant references on table "public"."users_private_details" to "anon";

grant select on table "public"."users_private_details" to "anon";

grant trigger on table "public"."users_private_details" to "anon";

grant truncate on table "public"."users_private_details" to "anon";

grant update on table "public"."users_private_details" to "anon";

grant delete on table "public"."users_private_details" to "authenticated";

grant insert on table "public"."users_private_details" to "authenticated";

grant references on table "public"."users_private_details" to "authenticated";

grant select on table "public"."users_private_details" to "authenticated";

grant trigger on table "public"."users_private_details" to "authenticated";

grant truncate on table "public"."users_private_details" to "authenticated";

grant update on table "public"."users_private_details" to "authenticated";

grant delete on table "public"."users_private_details" to "service_role";

grant insert on table "public"."users_private_details" to "service_role";

grant references on table "public"."users_private_details" to "service_role";

grant select on table "public"."users_private_details" to "service_role";

grant trigger on table "public"."users_private_details" to "service_role";

grant truncate on table "public"."users_private_details" to "service_role";

grant update on table "public"."users_private_details" to "service_role";

grant delete on table "public"."users_public_details" to "anon";

grant insert on table "public"."users_public_details" to "anon";

grant references on table "public"."users_public_details" to "anon";

grant select on table "public"."users_public_details" to "anon";

grant trigger on table "public"."users_public_details" to "anon";

grant truncate on table "public"."users_public_details" to "anon";

grant update on table "public"."users_public_details" to "anon";

grant delete on table "public"."users_public_details" to "authenticated";

grant insert on table "public"."users_public_details" to "authenticated";

grant references on table "public"."users_public_details" to "authenticated";

grant select on table "public"."users_public_details" to "authenticated";

grant trigger on table "public"."users_public_details" to "authenticated";

grant truncate on table "public"."users_public_details" to "authenticated";

grant update on table "public"."users_public_details" to "authenticated";

grant delete on table "public"."users_public_details" to "service_role";

grant insert on table "public"."users_public_details" to "service_role";

grant references on table "public"."users_public_details" to "service_role";

grant select on table "public"."users_public_details" to "service_role";

grant trigger on table "public"."users_public_details" to "service_role";

grant truncate on table "public"."users_public_details" to "service_role";

grant update on table "public"."users_public_details" to "service_role";

create policy "Enable read access for authenticated users"
on "public"."friends"
as permissive
for select
to authenticated
using (true);


create policy "Enable friends to view data"
on "public"."users_private_details"
as permissive
for select
to authenticated
using ((EXISTS ( SELECT 1
   FROM friends f
  WHERE (f.friend_id = auth.uid()))));


create policy "Enable users to view their own data only"
on "public"."users_private_details"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable read access for authenticated users"
on "public"."users_public_details"
as permissive
for select
to authenticated
using (true);



