create type "public"."task_interest_status" as enum ('pending', 'accepted', 'declined');

drop policy "Enable insert for users based on user_id" on "public"."tasks";

drop policy "Enable insert for users based on user_id" on "public"."users_public_details";

drop view if exists "public"."my_tasks";


  create table "public"."tasks_interests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "task_id" bigint not null,
    "user_id" uuid not null default auth.uid(),
    "status" public.task_interest_status not null default 'pending'::public.task_interest_status,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."tasks_interests" enable row level security;

CREATE UNIQUE INDEX tasks_interests_pkey ON public.tasks_interests USING btree (id);

CREATE UNIQUE INDEX tasks_interests_task_user_unique ON public.tasks_interests USING btree (task_id, user_id);

alter table "public"."tasks_interests" add constraint "tasks_interests_pkey" PRIMARY KEY using index "tasks_interests_pkey";

alter table "public"."tasks_interests" add constraint "tasks_interests_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks_interests" validate constraint "tasks_interests_task_id_fkey";

alter table "public"."tasks_interests" add constraint "tasks_interests_task_user_unique" UNIQUE using index "tasks_interests_task_user_unique";

alter table "public"."tasks_interests" add constraint "tasks_interests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks_interests" validate constraint "tasks_interests_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.set_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  begin
    new.updated_at = now();
    return new;
  end;
  $function$
;

CREATE OR REPLACE FUNCTION public.create_user_private_details()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  begin
    insert into public.users_private_details(user_id, email)
    values (new.id, new.email);
    return new;
  end;
  $function$
;

create or replace view "public"."my_details" as  SELECT private_details.user_id,
    public_details.nickname,
    public_details.avatar_url,
    private_details.email,
    private_details.phone,
    ((public_details.nickname IS NOT NULL) AND (public_details.avatar_url IS NOT NULL)) AS is_profile_completed
   FROM (public.users_private_details private_details
     LEFT JOIN public.users_public_details public_details ON ((private_details.user_id = public_details.user_id)))
  WHERE (private_details.user_id = ( SELECT auth.uid() AS uid));


create or replace view "public"."my_tasks" as  SELECT id,
    title,
    description,
    type,
    repeated_days
   FROM public.tasks
  WHERE (user_id = ( SELECT auth.uid() AS uid));


grant delete on table "public"."tasks_interests" to "anon";

grant insert on table "public"."tasks_interests" to "anon";

grant references on table "public"."tasks_interests" to "anon";

grant select on table "public"."tasks_interests" to "anon";

grant trigger on table "public"."tasks_interests" to "anon";

grant truncate on table "public"."tasks_interests" to "anon";

grant update on table "public"."tasks_interests" to "anon";

grant delete on table "public"."tasks_interests" to "authenticated";

grant insert on table "public"."tasks_interests" to "authenticated";

grant references on table "public"."tasks_interests" to "authenticated";

grant select on table "public"."tasks_interests" to "authenticated";

grant trigger on table "public"."tasks_interests" to "authenticated";

grant truncate on table "public"."tasks_interests" to "authenticated";

grant update on table "public"."tasks_interests" to "authenticated";

grant delete on table "public"."tasks_interests" to "service_role";

grant insert on table "public"."tasks_interests" to "service_role";

grant references on table "public"."tasks_interests" to "service_role";

grant select on table "public"."tasks_interests" to "service_role";

grant trigger on table "public"."tasks_interests" to "service_role";

grant truncate on table "public"."tasks_interests" to "service_role";

grant update on table "public"."tasks_interests" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."tasks_interests"
  as permissive
  for all
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."tasks_interests"
  as permissive
  for all
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."tasks"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."users_public_details"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));


CREATE TRIGGER set_updated_at_trigger BEFORE UPDATE ON public.tasks_interests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


