create schema if not exists "gis";

create extension if not exists "postgis" with schema "gis";
grant usage on schema gis to authenticated;

create type "public"."task_day" as enum ('sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat');

create type "public"."task_participation_status" as enum ('pending', 'accepted', 'declined', 'completed');

create type "public"."task_type" as enum ('offer', 'request');


  create table "public"."friends" (
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "friend_id" uuid not null
      );


alter table "public"."friends" enable row level security;


  create table "public"."participations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "task_id" bigint not null,
    "user_id" uuid not null default auth.uid(),
    "status" public.task_participation_status not null default 'pending'::public.task_participation_status,
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."participations" enable row level security;


  create table "public"."participations_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message" bytea not null,
    "expired_at" timestamp with time zone not null default (now() + '90 days'::interval),
    "sender_id" uuid not null default auth.uid(),
    "recipient_id" uuid not null,
    "participation_id" bigint not null
      );


alter table "public"."participations_messages" enable row level security;


  create table "public"."tasks" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "type" public.task_type not null,
    "title" text not null,
    "description" text,
    "repeated_days" public.task_day[],
    "created_at" timestamp with time zone not null default now(),
    "location" gis.geography(Point,4326) not null
      );


alter table "public"."tasks" enable row level security;


  create table "public"."users_private_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "email" text not null,
    "phone" text
      );


alter table "public"."users_private_details" enable row level security;


  create table "public"."users_public_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "nickname" text not null,
    "avatar_url" text
      );


alter table "public"."users_public_details" enable row level security;

CREATE UNIQUE INDEX friends_pkey ON public.friends USING btree (user_id, friend_id);

CREATE UNIQUE INDEX messages_pkey ON public.participations_messages USING btree (id);

CREATE UNIQUE INDEX participations_pkey ON public.participations USING btree (id);

CREATE UNIQUE INDEX participations_task_user_unique ON public.participations USING btree (task_id, user_id);

CREATE INDEX tasks_geo_index ON public.tasks USING gist (location);

CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);

CREATE UNIQUE INDEX users_private_details_email_key ON public.users_private_details USING btree (email);

CREATE UNIQUE INDEX users_private_details_phone_key ON public.users_private_details USING btree (phone);

CREATE UNIQUE INDEX users_private_details_pkey ON public.users_private_details USING btree (id);

CREATE UNIQUE INDEX users_private_details_user_id_key ON public.users_private_details USING btree (user_id);

CREATE UNIQUE INDEX users_public_details_nickname_key ON public.users_public_details USING btree (nickname);

CREATE UNIQUE INDEX users_public_details_pkey ON public.users_public_details USING btree (id);

CREATE UNIQUE INDEX users_public_details_user_id_key ON public.users_public_details USING btree (user_id);

alter table "public"."friends" add constraint "friends_pkey" PRIMARY KEY using index "friends_pkey";

alter table "public"."participations" add constraint "participations_pkey" PRIMARY KEY using index "participations_pkey";

alter table "public"."participations_messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."tasks" add constraint "tasks_pkey" PRIMARY KEY using index "tasks_pkey";

alter table "public"."users_private_details" add constraint "users_private_details_pkey" PRIMARY KEY using index "users_private_details_pkey";

alter table "public"."users_public_details" add constraint "users_public_details_pkey" PRIMARY KEY using index "users_public_details_pkey";

alter table "public"."friends" add constraint "friends_friend_id_fkey" FOREIGN KEY (friend_id) REFERENCES auth.users(id) not valid;

alter table "public"."friends" validate constraint "friends_friend_id_fkey";

alter table "public"."friends" add constraint "friends_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."friends" validate constraint "friends_user_id_fkey";

alter table "public"."friends" add constraint "user_cannot_be_friend_to_self" CHECK ((user_id <> friend_id)) not valid;

alter table "public"."friends" validate constraint "user_cannot_be_friend_to_self";

alter table "public"."participations" add constraint "participations_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."participations" validate constraint "participations_task_id_fkey";

alter table "public"."participations" add constraint "participations_task_user_unique" UNIQUE using index "participations_task_user_unique";

alter table "public"."participations" add constraint "participations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."participations" validate constraint "participations_user_id_fkey";

alter table "public"."participations_messages" add constraint "participations_messages_participation_id_fkey" FOREIGN KEY (participation_id) REFERENCES public.participations(id) ON DELETE CASCADE not valid;

alter table "public"."participations_messages" validate constraint "participations_messages_participation_id_fkey";

alter table "public"."participations_messages" add constraint "participations_messages_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES auth.users(id) not valid;

alter table "public"."participations_messages" validate constraint "participations_messages_recipient_id_fkey";

alter table "public"."participations_messages" add constraint "participations_messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."participations_messages" validate constraint "participations_messages_sender_id_fkey";

alter table "public"."participations_messages" add constraint "sender_not_equal_recipient" CHECK ((sender_id <> recipient_id)) not valid;

alter table "public"."participations_messages" validate constraint "sender_not_equal_recipient";

alter table "public"."tasks" add constraint "tasks_description_check" CHECK ((length(description) < 1000)) not valid;

alter table "public"."tasks" validate constraint "tasks_description_check";

alter table "public"."tasks" add constraint "tasks_title_check" CHECK ((length(title) < 200)) not valid;

alter table "public"."tasks" validate constraint "tasks_title_check";

alter table "public"."tasks" add constraint "tasks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."tasks" validate constraint "tasks_user_id_fkey";

alter table "public"."users_private_details" add constraint "users_private_details_email_key" UNIQUE using index "users_private_details_email_key";

alter table "public"."users_private_details" add constraint "users_private_details_phone_key" UNIQUE using index "users_private_details_phone_key";

alter table "public"."users_private_details" add constraint "users_private_details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_private_details" validate constraint "users_private_details_user_id_fkey";

alter table "public"."users_private_details" add constraint "users_private_details_user_id_key" UNIQUE using index "users_private_details_user_id_key";

alter table "public"."users_public_details" add constraint "users_public_details_nickname_key" UNIQUE using index "users_public_details_nickname_key";

alter table "public"."users_public_details" add constraint "users_public_details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_public_details" validate constraint "users_public_details_user_id_fkey";

alter table "public"."users_public_details" add constraint "users_public_details_user_id_key" UNIQUE using index "users_public_details_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_friend_after_participation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  task_owner uuid;
begin
  select user_id into task_owner
  from public.tasks
  where id = new.task_id;

  if task_owner is not null and task_owner <> new.user_id then
    insert into public.friends (user_id, friend_id)
    values (new.user_id, task_owner)
    on conflict do nothing;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_participation_message(p_participation_id bigint, p_message text)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
    declare
        v_allowed_sender boolean;
        v_my_uid uuid;
        v_recipient_from_task_owner uuid;
        v_recipient_from_participant uuid;
        v_recipient_id uuid;
        v_new_id bigint;
    begin
        select auth.uid() into v_my_uid;

        -- determine recipient id
        select p.user_id, t.user_id
            from public.participations p
            join public.tasks t on t.id = p.task_id
            where p.id = p_participation_id
            into v_recipient_from_participant, v_recipient_from_task_owner;

        if v_recipient_from_participant <> v_my_uid then
            v_recipient_id := v_recipient_from_participant;
        else
            v_recipient_id := v_recipient_from_task_owner;
        end if;

        insert into public.participations_messages(message, recipient_id, participation_id)
        values (
            public.encrypt_participation_message(p_participation_id, p_message), 
            v_recipient_id, 
            p_participation_id)
        returning id into v_new_id;

        return v_new_id;
    end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_secret_key_for_participation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
begin
  perform vault.create_secret(encode(extensions.gen_random_bytes(24), 'hex'), 'participation:' || new.id::text);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.create_user_private_details()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  begin
    insert into public.users_private_details(user_id, email)
    values (new.id, new.email);
    return new;
  end;
  $function$
;

CREATE OR REPLACE FUNCTION public.decrypt_participation_message(p_participation_id bigint, p_bytes bytea)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
    declare
        v_allowed_sender boolean;
        v_secret text;
        v_decrypted_text text;
    begin
        -- check if sender is either the participant or the task owner
        select exists (
            select 1
            from public.participations p
            join public.tasks t on t.id = p.task_id
            where p.id = p_participation_id
                and ((p.user_id = (select auth.uid())) or (t.user_id = (select auth.uid())))
        ) into v_allowed_sender;

        if not v_allowed_sender then
            raise exception 'Not allowed for this participation'
                using errcode = '42501';
        end if;

        -- retrieve the participation-specific secret
        select decrypted_secret
        into v_secret
        from vault.decrypted_secrets
        where name = 'participation:' || p_participation_id::text;

        if v_secret is null then
            raise exception 'Secret for participation not found'
                using errcode = 'P0001';
        end if;

        -- decrypt the provided message using the participation-specific secret
        v_decrypted_text := pgp_sym_decrypt(p_bytes, v_secret);
        return v_decrypted_text;
    end;
$function$
;

CREATE OR REPLACE FUNCTION public.encrypt_participation_message(p_participation_id bigint, p_message text)
 RETURNS bytea
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
    declare
        v_secret text;
        v_encrypted_text bytea;
    begin
        select decrypted_secret
        into v_secret
        from vault.decrypted_secrets
        where name = 'participation:' || p_participation_id::text;

        if v_secret is null then
            raise exception 'Secret for participation not found'
                using errcode = 'P0001';
        end if;

        -- decrypt the provided message using the participation-specific secret
        v_encrypted_text := pgp_sym_encrypt(p_message, v_secret, 'compress-algo=1, cipher-algo=aes256');
        return v_encrypted_text;
    end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_task_details(input_task_id bigint)
 RETURNS TABLE(id bigint, user_id uuid, user_nickname text, user_avatar_url text, type public.task_type, title text, description text, repeated_days public.task_day[], lat double precision, lng double precision)
 LANGUAGE sql
 SET search_path TO ''
AS $function$
select
  t.id, 
  t.user_id,
  public_details.nickname,
  public_details.avatar_url,
  t.type, 
  t.title, 
  t.description, 
  t.repeated_days, 
  gis.st_y(t.location::gis.geometry) as lat,
  gis.st_x(t.location::gis.geometry) as lng
FROM public.tasks t
LEFT JOIN public.users_public_details public_details
  ON public_details.user_id = t.user_id
WHERE t.id = input_task_id
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_task_participations(p_task_id bigint)
 RETURNS TABLE(id bigint, status public.task_participation_status, updated_at timestamp with time zone, user_nickname text, user_avatar_url text)
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
select
  p.id,
  p.status,
  p.updated_at,
  upd.nickname as user_nickname,
  upd.avatar_url as user_avatar_url
from
  participations p
  join users_public_details upd on upd.user_id = p.user_id
where
  p.task_id = p_task_id;
$function$
;

CREATE OR REPLACE FUNCTION public.get_nearby_tasks(user_lat double precision, user_lng double precision, distance_meters integer)
 RETURNS TABLE(id bigint, user_id uuid, type public.task_type, title text, description text, repeated_days public.task_day[], is_me boolean, distance_meters integer)
 LANGUAGE sql
 SET search_path TO ''
AS $function$
select
  id,
  user_id,
  type,
  title,
  description,
  repeated_days,
  public.is_me(tasks.user_id) as is_me,
  round(gis.st_distance(public.tasks.location, gis.st_point(user_lng, user_lat)::gis.geography))::int as distance_meters
from
  public.tasks
  where gis.ST_DWithin(
        location,
        gis.ST_SetSRID(gis.ST_MakePoint(user_lng, user_lat), 4326)::gis.geography,
        distance_meters
    ) AND user_id <> (SELECT auth.uid())
  order by location operator(gis.<->) gis.st_point(user_lng, user_lat)::gis.geography;
$function$
;

CREATE OR REPLACE FUNCTION public.get_participation_messages(p_participation_id bigint)
 RETURNS TABLE(id bigint, message text, created_at timestamp with time zone, sender_nickname text, sender_avatar_url text, recipient_nickname text, recipient_avatar_url text, sent_by_me boolean)
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
    return query
        select
            pm.id,
            public.decrypt_participation_message(p_participation_id, pm.message) as message,
            pm.created_at,
            upd_sender.nickname as sender_nickname,
            upd_sender.avatar_url as sender_avatar_url,
            upd_recipient.nickname as recipient_nickname,
            upd_recipient.avatar_url as recipient_avatar_url,
            (pm.sender_id = (select auth.uid())) as sent_by_me
        from participations_messages pm
        join users_public_details upd_sender on upd_sender.user_id = pm.sender_id
        join users_public_details upd_recipient on upd_recipient.user_id = pm.recipient_id
        where pm.participation_id = p_participation_id
        order by created_at asc;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_task_details(input_task_id bigint, current_lat double precision DEFAULT NULL::double precision, current_lng double precision DEFAULT NULL::double precision)
 RETURNS TABLE(id bigint, user_id uuid, user_nickname text, user_avatar_url text, type public.task_type, title text, description text, repeated_days public.task_day[], is_me boolean, distance_meters integer, lat double precision, lng double precision, participation_status public.task_participation_status, participation_updated_at timestamp with time zone)
 LANGUAGE sql
 SET search_path TO ''
AS $function$
select
  t.id,
  t.user_id,
  public_details.nickname,
  public_details.avatar_url,
  t.type, 
  t.title, 
  t.description, 
  t.repeated_days, 
  public.is_me(t.user_id) as is_me,
  CASE 
    WHEN current_lat IS NOT NULL AND current_lng IS NOT NULL THEN
      round(gis.st_distance(t.location, gis.st_point(current_lng, current_lat)::gis.geography))::int
    ELSE 
      NULL 
  END AS distance_meters,
  gis.st_y(t.location::gis.geometry) as lat,
  gis.st_x(t.location::gis.geometry) as lng,
  prtcs.status as participation_status,
  prtcs.updated_at as participation_updated_at
FROM public.tasks t
LEFT JOIN public.users_public_details public_details
  ON public_details.user_id = t.user_id
LEFT JOIN public.participations prtcs
  ON prtcs.task_id = t.id
WHERE t.id = input_task_id
$function$
;

CREATE OR REPLACE FUNCTION public.is_me(check_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
    select check_user_id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.is_my_task(task_id bigint)
 RETURNS boolean
 LANGUAGE sql
 SET search_path TO ''
AS $function$
  select exists (
    select 1
    from public.tasks
    where id = task_id
      and user_id = auth.uid()
  );
$function$
;

create or replace view "public"."my_details" with (security_invoker = on) as  SELECT private_details.user_id,
    public_details.nickname,
    public_details.avatar_url,
    private_details.email,
    private_details.phone,
    ((public_details.nickname IS NOT NULL) AND (public_details.avatar_url IS NOT NULL)) AS is_profile_completed
   FROM (public.users_private_details private_details
     LEFT JOIN public.users_public_details public_details ON ((private_details.user_id = public_details.user_id)))
  WHERE (private_details.user_id = ( SELECT auth.uid() AS uid));


create or replace view "public"."my_tasks" with (security_invoker = on) as  SELECT id,
    title,
    description,
    type,
    repeated_days
   FROM public.tasks
  WHERE (user_id = ( SELECT auth.uid() AS uid));


CREATE OR REPLACE FUNCTION public.set_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  begin
    new.updated_at = now();
    return new;
  end;
  $function$
;

grant delete on table "public"."friends" to "anon";

grant insert on table "public"."friends" to "anon";

grant references on table "public"."friends" to "anon";

grant select on table "public"."friends" to "anon";

grant trigger on table "public"."friends" to "anon";

grant truncate on table "public"."friends" to "anon";

grant update on table "public"."friends" to "anon";

grant delete on table "public"."friends" to "authenticated";

grant insert on table "public"."friends" to "authenticated";

grant references on table "public"."friends" to "authenticated";

grant select on table "public"."friends" to "authenticated";

grant trigger on table "public"."friends" to "authenticated";

grant truncate on table "public"."friends" to "authenticated";

grant update on table "public"."friends" to "authenticated";

grant delete on table "public"."friends" to "service_role";

grant insert on table "public"."friends" to "service_role";

grant references on table "public"."friends" to "service_role";

grant select on table "public"."friends" to "service_role";

grant trigger on table "public"."friends" to "service_role";

grant truncate on table "public"."friends" to "service_role";

grant update on table "public"."friends" to "service_role";

grant delete on table "public"."participations" to "anon";

grant insert on table "public"."participations" to "anon";

grant references on table "public"."participations" to "anon";

grant select on table "public"."participations" to "anon";

grant trigger on table "public"."participations" to "anon";

grant truncate on table "public"."participations" to "anon";

grant update on table "public"."participations" to "anon";

grant delete on table "public"."participations" to "authenticated";

grant insert on table "public"."participations" to "authenticated";

grant references on table "public"."participations" to "authenticated";

grant select on table "public"."participations" to "authenticated";

grant trigger on table "public"."participations" to "authenticated";

grant truncate on table "public"."participations" to "authenticated";

grant update on table "public"."participations" to "authenticated";

grant delete on table "public"."participations" to "service_role";

grant insert on table "public"."participations" to "service_role";

grant references on table "public"."participations" to "service_role";

grant select on table "public"."participations" to "service_role";

grant trigger on table "public"."participations" to "service_role";

grant truncate on table "public"."participations" to "service_role";

grant update on table "public"."participations" to "service_role";

grant delete on table "public"."participations_messages" to "anon";

grant insert on table "public"."participations_messages" to "anon";

grant references on table "public"."participations_messages" to "anon";

grant select on table "public"."participations_messages" to "anon";

grant trigger on table "public"."participations_messages" to "anon";

grant truncate on table "public"."participations_messages" to "anon";

grant update on table "public"."participations_messages" to "anon";

grant delete on table "public"."participations_messages" to "authenticated";

grant insert on table "public"."participations_messages" to "authenticated";

grant references on table "public"."participations_messages" to "authenticated";

grant select on table "public"."participations_messages" to "authenticated";

grant trigger on table "public"."participations_messages" to "authenticated";

grant truncate on table "public"."participations_messages" to "authenticated";

grant update on table "public"."participations_messages" to "authenticated";

grant delete on table "public"."participations_messages" to "service_role";

grant insert on table "public"."participations_messages" to "service_role";

grant references on table "public"."participations_messages" to "service_role";

grant select on table "public"."participations_messages" to "service_role";

grant trigger on table "public"."participations_messages" to "service_role";

grant truncate on table "public"."participations_messages" to "service_role";

grant update on table "public"."participations_messages" to "service_role";

grant delete on table "public"."tasks" to "anon";

grant insert on table "public"."tasks" to "anon";

grant references on table "public"."tasks" to "anon";

grant select on table "public"."tasks" to "anon";

grant trigger on table "public"."tasks" to "anon";

grant truncate on table "public"."tasks" to "anon";

grant update on table "public"."tasks" to "anon";

grant delete on table "public"."tasks" to "authenticated";

grant insert on table "public"."tasks" to "authenticated";

grant references on table "public"."tasks" to "authenticated";

grant select on table "public"."tasks" to "authenticated";

grant trigger on table "public"."tasks" to "authenticated";

grant truncate on table "public"."tasks" to "authenticated";

grant update on table "public"."tasks" to "authenticated";

grant delete on table "public"."tasks" to "service_role";

grant insert on table "public"."tasks" to "service_role";

grant references on table "public"."tasks" to "service_role";

grant select on table "public"."tasks" to "service_role";

grant trigger on table "public"."tasks" to "service_role";

grant truncate on table "public"."tasks" to "service_role";

grant update on table "public"."tasks" to "service_role";

grant delete on table "public"."users_private_details" to "anon";

grant insert on table "public"."users_private_details" to "anon";

grant references on table "public"."users_private_details" to "anon";

grant select on table "public"."users_private_details" to "anon";

grant trigger on table "public"."users_private_details" to "anon";

grant truncate on table "public"."users_private_details" to "anon";

grant update on table "public"."users_private_details" to "anon";

grant delete on table "public"."users_private_details" to "authenticated";

grant insert on table "public"."users_private_details" to "authenticated";

grant references on table "public"."users_private_details" to "authenticated";

grant select on table "public"."users_private_details" to "authenticated";

grant trigger on table "public"."users_private_details" to "authenticated";

grant truncate on table "public"."users_private_details" to "authenticated";

grant update on table "public"."users_private_details" to "authenticated";

grant delete on table "public"."users_private_details" to "service_role";

grant insert on table "public"."users_private_details" to "service_role";

grant references on table "public"."users_private_details" to "service_role";

grant select on table "public"."users_private_details" to "service_role";

grant trigger on table "public"."users_private_details" to "service_role";

grant truncate on table "public"."users_private_details" to "service_role";

grant update on table "public"."users_private_details" to "service_role";

grant delete on table "public"."users_public_details" to "anon";

grant insert on table "public"."users_public_details" to "anon";

grant references on table "public"."users_public_details" to "anon";

grant select on table "public"."users_public_details" to "anon";

grant trigger on table "public"."users_public_details" to "anon";

grant truncate on table "public"."users_public_details" to "anon";

grant update on table "public"."users_public_details" to "anon";

grant delete on table "public"."users_public_details" to "authenticated";

grant insert on table "public"."users_public_details" to "authenticated";

grant references on table "public"."users_public_details" to "authenticated";

grant select on table "public"."users_public_details" to "authenticated";

grant trigger on table "public"."users_public_details" to "authenticated";

grant truncate on table "public"."users_public_details" to "authenticated";

grant update on table "public"."users_public_details" to "authenticated";

grant delete on table "public"."users_public_details" to "service_role";

grant insert on table "public"."users_public_details" to "service_role";

grant references on table "public"."users_public_details" to "service_role";

grant select on table "public"."users_public_details" to "service_role";

grant trigger on table "public"."users_public_details" to "service_role";

grant truncate on table "public"."users_public_details" to "service_role";

grant update on table "public"."users_public_details" to "service_role";


  create policy "Enable read access for authenticated users"
  on "public"."friends"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for users based on user_id"
  on "public"."participations"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view items for their tasks only"
  on "public"."participations"
  as permissive
  for select
  to authenticated
using ((public.is_my_task(task_id) OR (user_id = ( SELECT auth.uid() AS uid))));



  create policy "Allow message access for sender or recipient"
  on "public"."participations_messages"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = sender_id) OR (( SELECT auth.uid() AS uid) = recipient_id)));



  create policy "Allow participants or owners to insert messages"
  on "public"."participations_messages"
  as permissive
  for insert
  to authenticated
with check (((( SELECT auth.uid() AS uid) = sender_id) AND (EXISTS ( SELECT 1
   FROM (public.participations p
     JOIN public.tasks t ON ((t.id = p.task_id)))
  WHERE ((p.id = participations_messages.participation_id) AND ((p.user_id = ( SELECT auth.uid() AS uid)) OR (t.user_id = ( SELECT auth.uid() AS uid))) AND ((participations_messages.recipient_id = p.user_id) OR (participations_messages.recipient_id = t.user_id)))))));



  create policy "Enable insert for users based on user_id"
  on "public"."tasks"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for authenticated users"
  on "public"."tasks"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable owners and those friends to view private details"
  on "public"."users_private_details"
  as permissive
  for select
  to authenticated
using (((user_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM public.friends f
  WHERE (f.friend_id = ( SELECT auth.uid() AS uid))))));



  create policy "Enable insert for users based on user_id"
  on "public"."users_public_details"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for authenticated users"
  on "public"."users_public_details"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER create_friend_after_participation_trigger AFTER INSERT ON public.participations FOR EACH ROW EXECUTE FUNCTION public.create_friend_after_participation();

CREATE TRIGGER create_secret_key_after_participation_trigger AFTER INSERT ON public.participations FOR EACH ROW EXECUTE FUNCTION public.create_secret_key_for_participation();

CREATE TRIGGER set_updated_at_trigger BEFORE UPDATE ON public.participations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();

CREATE TRIGGER auth_users_insert_trigger AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_user_private_details();


